// GPM — sample data
// Neon People team's projects (recruiting / hiring / people tech)

const TEAM = {
  vc: { id:'vc', name:'Vanessa Costa',    role:'Líder de People Tech',  initials:'VC', color:'#008fff', load:78 },
  ba: { id:'ba', name:'Bruno Almeida',    role:'Eng. Lead',             initials:'BA', color:'#0000d3', load:92 },
  ls: { id:'ls', name:'Larissa Souza',    role:'Product Designer',      initials:'LS', color:'#00aaa3', load:64 },
  df: { id:'df', name:'Diego Ferraz',     role:'Software Eng.',         initials:'DF', color:'#5a1aa0', load:108 },
  ml: { id:'ml', name:'Marina Lima',      role:'People Partner',        initials:'ML', color:'#c47b00', load:52 },
  ro: { id:'ro', name:'Renato Oliveira',  role:'Data Analyst',          initials:'RO', color:'#2c8a00', load:71 },
  pj: { id:'pj', name:'Paula Jorge',      role:'People Ops',            initials:'PJ', color:'#a20025', load:84 },
};

const T = TEAM;

// Status: progress | discovery | risk | blocked | done | paused | planning
const PROJECTS = [
  {
    id:'p1',
    name:'POC: Entrevistas com IA',
    sub:'Avaliação automática de entrevistas técnicas',
    icon:'🤖', tint:'#e6f4ff',
    status:'progress',
    progress: 62,
    health:'warn',
    owner: T.ba,
    team: [T.ba, T.df, T.ls, T.ro],
    due: '12 jun',
    dueDate: 12,
    dueMonth: 'jun',
    dueWarn: 'warn',
    tasks: { total: 24, done: 15, blocked: 1 },
    tag:'POC',
    quarter: 'Q2',
    start: 1, end: 4.2, // gantt position (0-6 = 6 months)
  },
  {
    id:'p2',
    name:'POC: Hunting Assistant LinkedIn',
    sub:'Sourcing automatizado de candidatos no LinkedIn',
    icon:'🎯', tint:'#f1e7ff',
    status:'discovery',
    progress: 28,
    health:'ok',
    owner: T.vc,
    team: [T.vc, T.ml, T.df],
    due: '30 jun',
    dueDate: 30,
    dueMonth: 'jun',
    tasks: { total: 18, done: 5, blocked: 0 },
    tag:'POC',
    quarter: 'Q2',
    start: 1.4, end: 4.6,
  },
  {
    id:'p3',
    name:'Farol de Vagas',
    sub:'Dashboard de vagas abertas, tempo médio, funil',
    icon:'🛰️', tint:'#e2f7ff',
    status:'progress',
    progress: 74,
    health:'ok',
    owner: T.ro,
    team: [T.ro, T.ls, T.vc],
    due: '28 mai',
    dueDate: 28,
    dueMonth: 'mai',
    tasks: { total: 32, done: 24, blocked: 0 },
    tag:'Produto',
    quarter: 'Q2',
    start: 0.3, end: 2.8,
  },
  {
    id:'p4',
    name:'Parecer de Entrevista',
    sub:'Padronização e captura estruturada de feedbacks',
    icon:'📝', tint:'#ddffc7',
    status:'progress',
    progress: 89,
    health:'ok',
    owner: T.ls,
    team: [T.ls, T.df, T.pj],
    due: '24 mai',
    dueDate: 24,
    dueMonth: 'mai',
    tasks: { total: 21, done: 19, blocked: 0 },
    tag:'Produto',
    quarter: 'Q2',
    start: 0, end: 2.5,
  },
  {
    id:'p5',
    name:'Abertura de Vagas',
    sub:'Fluxo self-service para líderes abrirem vagas',
    icon:'📋', tint:'#fff4d6',
    status:'risk',
    progress: 41,
    health:'warn',
    owner: T.vc,
    team: [T.vc, T.df, T.ba, T.ml],
    due: '07 jun',
    dueDate: 7,
    dueMonth: 'jun',
    dueWarn: 'warn',
    tasks: { total: 28, done: 11, blocked: 2 },
    tag:'Produto',
    quarter: 'Q2',
    start: 0.6, end: 3.4,
  },
  {
    id:'p6',
    name:'Automação de Agendas',
    sub:'Agendamento automático de entrevistas multi-painel',
    icon:'📅', tint:'#e6f4ff',
    status:'blocked',
    progress: 35,
    health:'bad',
    owner: T.df,
    team: [T.df, T.pj],
    due: '18 jun',
    dueDate: 18,
    dueMonth: 'jun',
    tasks: { total: 16, done: 5, blocked: 3 },
    tag:'Automação',
    quarter: 'Q2',
    start: 1.8, end: 4.8,
  },
  {
    id:'p7',
    name:'Simulação de Offer',
    sub:'Calculadora pra simular pacotes de remuneração',
    icon:'💰', tint:'#f1ffd9',
    status:'planning',
    progress: 12,
    health:'idle',
    owner: T.ml,
    team: [T.ml, T.ro, T.ls],
    due: '15 jul',
    dueDate: 15,
    dueMonth: 'jul',
    tasks: { total: 14, done: 1, blocked: 0 },
    tag:'Produto',
    quarter: 'Q3',
    start: 3.5, end: 5.8,
  },
  {
    id:'p8',
    name:'Movimentações',
    sub:'Promoções, transferências e mudanças de cargo',
    icon:'🔁', tint:'#f1e7ff',
    status:'progress',
    progress: 55,
    health:'ok',
    owner: T.pj,
    team: [T.pj, T.vc, T.ro],
    due: '20 jun',
    dueDate: 20,
    dueMonth: 'jun',
    tasks: { total: 19, done: 10, blocked: 0 },
    tag:'Produto',
    quarter: 'Q2',
    start: 1.2, end: 4.4,
  },
  {
    id:'p9',
    name:'People Agent',
    sub:'Assistente conversacional pra colaboradores',
    icon:'✨', tint:'#e6f4ff',
    status:'discovery',
    progress: 18,
    health:'ok',
    owner: T.ba,
    team: [T.ba, T.df, T.ls, T.vc],
    due: '01 ago',
    dueDate: 1,
    dueMonth: 'ago',
    tasks: { total: 12, done: 2, blocked: 0 },
    tag:'POC',
    quarter: 'Q3',
    start: 2.8, end: 6,
  },
  {
    id:'p10',
    name:'Dashboard Líder',
    sub:'Visão consolidada de time pra gestores',
    icon:'📊', tint:'#ddffc7',
    status:'done',
    progress: 100,
    health:'ok',
    owner: T.ro,
    team: [T.ro, T.ls, T.vc],
    due: '10 mai',
    dueDate: 10,
    dueMonth: 'mai',
    dueWarn: 'done',
    tasks: { total: 26, done: 26, blocked: 0 },
    tag:'Produto',
    quarter: 'Q2',
    start: 0, end: 2,
  },
  {
    id:'p11',
    name:'Implantação Teamguide',
    sub:'Rollout do Teamguide pra todos os squads',
    icon:'🚀', tint:'#fff4d6',
    status:'risk',
    progress: 47,
    health:'warn',
    owner: T.ml,
    team: [T.ml, T.pj, T.vc],
    due: '30 jun',
    dueDate: 30,
    dueMonth: 'jun',
    dueWarn: 'warn',
    tasks: { total: 22, done: 9, blocked: 1 },
    tag:'Implantação',
    quarter: 'Q2',
    start: 1, end: 4.5,
  },
];

const STATUS_LABEL = {
  progress: 'Em andamento',
  discovery: 'Discovery',
  risk: 'Em risco',
  blocked: 'Bloqueado',
  done: 'Concluído',
  paused: 'Pausado',
  planning: 'Planejamento',
};

const ACTIVITY = [
  { who: T.df, text: <span>moveu <strong>Integração com Greenhouse</strong> para <em>Em revisão</em></span>, time: 'há 12 min', proj: 'p1' },
  { who: T.ls, text: <span>compartilhou os mockups de <strong>Parecer de Entrevista</strong></span>, time: 'há 38 min', proj: 'p4' },
  { who: T.vc, text: <span>marcou <strong>Abertura de Vagas</strong> como <em>Em risco</em></span>, time: 'há 1h', proj: 'p5' },
  { who: T.ro, text: <span>publicou <strong>Farol de Vagas v2</strong> em homologação</span>, time: 'há 2h', proj: 'p3' },
  { who: T.ba, text: <span>concluiu <strong>Spike: modelos de avaliação</strong></span>, time: 'há 4h', proj: 'p1' },
  { who: T.pj, text: <span>criou tarefa <strong>Comunicado de Movimentações</strong></span>, time: 'ontem', proj: 'p8' },
];

const UPCOMING = [
  { title:'Aprovar fluxo de Abertura de Vagas', proj:'Abertura de Vagas', due:'amanhã', owner: T.vc, late:false, done:false },
  { title:'Review final · Parecer de Entrevista', proj:'Parecer de Entrevista', due:'qui · 23 mai', owner: T.ls, late:false, done:false },
  { title:'Liberar Farol v2 em homologação', proj:'Farol de Vagas', due:'qui · 23 mai', owner: T.ro, late:false, done:true },
  { title:'Desbloquear API de calendário', proj:'Automação de Agendas', due:'hoje', owner: T.df, late:true, done:false },
  { title:'Sessão de research com líderes', proj:'POC: Hunting Assistant', due:'sex · 24 mai', owner: T.vc, late:false, done:false },
  { title:'Apresentar POC pra liderança', proj:'POC: Entrevistas com IA', due:'seg · 27 mai', owner: T.ba, late:false, done:false },
];

// Kanban — tasks across all projects (one realistic spread)
const KANBAN_COLS = [
  { id:'backlog', title:'Backlog', count: 18 },
  { id:'todo', title:'A fazer', count: 9 },
  { id:'doing', title:'Em andamento', count: 7 },
  { id:'review', title:'Em revisão', count: 4 },
  { id:'done', title:'Concluído', count: 12 },
];

const KANBAN_TASKS = {
  backlog: [
    { name:'Auditoria de pipeline de Hunting', proj:'POC: Hunting Assistant', tag:'POC', tagColor:'#f1e7ff', tagFg:'#5a1aa0', owner: T.vc, comments: 2 },
    { name:'Mapear personas de gestores', proj:'Dashboard Líder', tag:'Produto', tagColor:'#e6f4ff', tagFg:'#005699', owner: T.ls, comments: 0 },
    { name:'Definir métricas-base do Farol', proj:'Farol de Vagas', tag:'Produto', tagColor:'#e6f4ff', tagFg:'#005699', owner: T.ro, comments: 1 },
  ],
  todo: [
    { name:'Roteiro de pesquisa com candidatos', proj:'Parecer de Entrevista', tag:'Discovery', tagColor:'#f1e7ff', tagFg:'#5a1aa0', owner: T.ls, due:'amanhã', comments: 3 },
    { name:'Especificar API de calendário', proj:'Automação de Agendas', tag:'Bloqueado', tagColor:'#ffe0e6', tagFg:'#a20025', owner: T.df, due:'hoje', comments: 5, blocked: true },
    { name:'Onboarding Teamguide · piloto', proj:'Implantação Teamguide', tag:'Implantação', tagColor:'#fff4d6', tagFg:'#8a6100', owner: T.ml, due:'qui', comments: 1 },
  ],
  doing: [
    { name:'Integração Greenhouse → Farol', proj:'Farol de Vagas', tag:'Produto', tagColor:'#e6f4ff', tagFg:'#005699', owner: T.ro, due:'qui', comments: 4 },
    { name:'Treinar modelo de scoring', proj:'POC: Entrevistas com IA', tag:'POC', tagColor:'#f1e7ff', tagFg:'#5a1aa0', owner: T.ba, due:'sex', comments: 8 },
    { name:'Fluxo self-service de Abertura', proj:'Abertura de Vagas', tag:'Produto', tagColor:'#e6f4ff', tagFg:'#005699', owner: T.df, due:'hoje', comments: 2, warn: true },
  ],
  review: [
    { name:'Mockups Parecer de Entrevista', proj:'Parecer de Entrevista', tag:'Design', tagColor:'#e2f7ff', tagFg:'#006080', owner: T.ls, due:'amanhã', comments: 6 },
    { name:'Calc. de pacote de remuneração', proj:'Simulação de Offer', tag:'Produto', tagColor:'#e6f4ff', tagFg:'#005699', owner: T.ml, due:'25 mai', comments: 2 },
  ],
  done: [
    { name:'Spike: modelos de avaliação', proj:'POC: Entrevistas com IA', tag:'POC', tagColor:'#f1e7ff', tagFg:'#5a1aa0', owner: T.ba, comments: 3 },
    { name:'Dashboard Líder · v1', proj:'Dashboard Líder', tag:'Produto', tagColor:'#ddffc7', tagFg:'#2c5e00', owner: T.ro, comments: 5 },
    { name:'Validação com 5 líderes', proj:'Dashboard Líder', tag:'Research', tagColor:'#ddffc7', tagFg:'#2c5e00', owner: T.vc, comments: 4 },
  ],
};

// Calendar events for May 2026
const CAL_EVENTS = {
  20: [{ name:'Apresentação POC IA', color:'#e6f4ff', fg:'#005699' }],
  22: [{ name:'Review · Parecer', color:'#e2f7ff', fg:'#006080' }],
  23: [{ name:'Farol v2 → homolog', color:'#ddffc7', fg:'#2c5e00' }, { name:'1:1 Bruno', color:'#fff4d6', fg:'#8a6100' }],
  24: [{ name:'Pesquisa · Hunting', color:'#f1e7ff', fg:'#5a1aa0' }],
  27: [{ name:'POC IA → liderança', color:'#e6f4ff', fg:'#005699' }],
  28: [{ name:'Farol de Vagas · GA', color:'#ddffc7', fg:'#2c5e00' }],
  30: [{ name:'Comitê de People Tech', color:'#fff4d6', fg:'#8a6100' }],
};

Object.assign(window, { TEAM, PROJECTS, STATUS_LABEL, ACTIVITY, UPCOMING, KANBAN_COLS, KANBAN_TASKS, CAL_EVENTS });
